//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xapi.Ruby/", ConfigurationName="SMSWebService.XAService")]
    public interface XAService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xapi.Ruby/XAService/sendMessageRequest", ReplyAction="http://xapi.Ruby/XAService/sendMessageResponse")]
        System.Threading.Tasks.Task<SMSWebService.sendMessageResponse> sendMessageAsync(SMSWebService.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://xapi.Ruby/XAService/sendAirtimeRequest", ReplyAction="http://xapi.Ruby/XAService/sendAirtimeResponse")]
        System.Threading.Tasks.Task<SMSWebService.sendAirtimeResponse> sendAirtimeAsync(SMSWebService.sendAirtimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://xapi.Ruby/", Order=0)]
        public SMSWebService.sendMessageRequestBody Body;
        
        public sendMessageRequest()
        {
        }
        
        public sendMessageRequest(SMSWebService.sendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string alertId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public sendMessageRequestBody()
        {
        }
        
        public sendMessageRequestBody(string alertId, string mobileNumber, string message)
        {
            this.alertId = alertId;
            this.mobileNumber = mobileNumber;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://xapi.Ruby/", Order=0)]
        public SMSWebService.sendMessageResponseBody Body;
        
        public sendMessageResponse()
        {
        }
        
        public sendMessageResponse(SMSWebService.sendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public sendMessageResponseBody()
        {
        }
        
        public sendMessageResponseBody(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAirtimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAirtime", Namespace="http://xapi.Ruby/", Order=0)]
        public SMSWebService.sendAirtimeRequestBody Body;
        
        public sendAirtimeRequest()
        {
        }
        
        public sendAirtimeRequest(SMSWebService.sendAirtimeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendAirtimeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool prepaid;
        
        public sendAirtimeRequestBody()
        {
        }
        
        public sendAirtimeRequestBody(string reference, string mobileNumber, int amount, bool prepaid)
        {
            this.reference = reference;
            this.mobileNumber = mobileNumber;
            this.amount = amount;
            this.prepaid = prepaid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAirtimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAirtimeResponse", Namespace="http://xapi.Ruby/", Order=0)]
        public SMSWebService.sendAirtimeResponseBody Body;
        
        public sendAirtimeResponse()
        {
        }
        
        public sendAirtimeResponse(SMSWebService.sendAirtimeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendAirtimeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendAirtimeResponseBody()
        {
        }
        
        public sendAirtimeResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface XAServiceChannel : SMSWebService.XAService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class XAServiceClient : System.ServiceModel.ClientBase<SMSWebService.XAService>, SMSWebService.XAService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XAServiceClient() : 
                base(XAServiceClient.GetDefaultBinding(), XAServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.XAServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XAServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(XAServiceClient.GetBindingForEndpoint(endpointConfiguration), XAServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XAServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XAServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XAServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XAServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSWebService.sendMessageResponse> SMSWebService.XAService.sendMessageAsync(SMSWebService.sendMessageRequest request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSWebService.sendMessageResponse> sendMessageAsync(string alertId, string mobileNumber, string message)
        {
            SMSWebService.sendMessageRequest inValue = new SMSWebService.sendMessageRequest();
            inValue.Body = new SMSWebService.sendMessageRequestBody();
            inValue.Body.alertId = alertId;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.message = message;
            return ((SMSWebService.XAService)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSWebService.sendAirtimeResponse> SMSWebService.XAService.sendAirtimeAsync(SMSWebService.sendAirtimeRequest request)
        {
            return base.Channel.sendAirtimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSWebService.sendAirtimeResponse> sendAirtimeAsync(string reference, string mobileNumber, int amount, bool prepaid)
        {
            SMSWebService.sendAirtimeRequest inValue = new SMSWebService.sendAirtimeRequest();
            inValue.Body = new SMSWebService.sendAirtimeRequestBody();
            inValue.Body.reference = reference;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.amount = amount;
            inValue.Body.prepaid = prepaid;
            return ((SMSWebService.XAService)(this)).sendAirtimeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XAServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XAServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.60.5:3900/ruby/xapi");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return XAServiceClient.GetBindingForEndpoint(EndpointConfiguration.XAServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return XAServiceClient.GetEndpointAddress(EndpointConfiguration.XAServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            XAServicePort,
        }
    }
}
