using SMS.Domain.Lookups;

namespace SMS.Persistence
{
    public static class CountrySeedData
    {

        public static async Task SeedAsync(SMSDbContext dbContext)
        {
            if (!dbContext.Countries.Any())
            {
                await dbContext.Countries.AddRangeAsync(Countries);
            }
        }

        private static List<Country> Countries => new List<Country>() {
            new Country() { Name = "Afghanistan", Code="AFG", Nationality = "Afghan" },
            new Country() { Name = "Åland Islands", Code="ALA", Nationality = "Åland Island" },
            new Country() { Name = "Albania", Code="ALB", Nationality = "Albanian" },
            new Country() { Name = "Algeria", Code="DZA", Nationality = "Algerian" },
            new Country() { Name = "American Samoa", Code="ASM", Nationality = "American Samoan" },
            new Country() { Name = "Andorra", Code="AND", Nationality = "Andorran" },
            new Country() { Name = "Angola", Code="AGO", Nationality = "Angolan" },
            new Country() { Name = "Anguilla", Code="AIA", Nationality = "Anguillan" },
            new Country() { Name = "Antarctica", Code="ATA", Nationality = "Antarctic" },
            new Country() { Name = "Antigua and Barbuda", Code="ATG", Nationality = "Antiguan or Barbudan" },
            new Country() { Name = "Argentina", Code="ARG", Nationality = "Argentine" },
            new Country() { Name = "Armenia", Code="ARM", Nationality = "Armenian" },
            new Country() { Name = "Aruba", Code="ABW", Nationality = "Aruban" },
            new Country() { Name = "Australia", Code="AUS", Nationality = "Australian" },
            new Country() { Name = "Austria", Code="AUT", Nationality = "Austrian" },
            new Country() { Name = "Azerbaijan", Code="AZE", Nationality = "Azerbaijani, Azeri" },
            new Country() { Name = "Bahamas", Code="BHS", Nationality = "Bahamian" },
            new Country() { Name = "Bahrain", Code="BHR", Nationality = "Bahraini" },
            new Country() { Name = "Bangladesh", Code="BGD", Nationality = "Bangladeshi" },
            new Country() { Name = "Barbados", Code="BRB", Nationality = "Barbadian" },
            new Country() { Name = "Belarus", Code="BLR", Nationality = "Belarusian" },
            new Country() { Name = "Belgium", Code="BEL", Nationality = "Belgian" },
            new Country() { Name = "Belize", Code="BLZ", Nationality = "Belizean" },
            new Country() { Name = "Benin", Code="BEN", Nationality = "Beninese, Beninois" },
            new Country() { Name = "Bermuda", Code="BMU", Nationality = "Bermudian, Bermudan" },
            new Country() { Name = "Bhutan", Code="BTN", Nationality = "Bhutanese" },
            new Country() { Name = "Bolivia (Plurinational State of)", Code="BOL", Nationality = "Bolivian" },
            new Country() { Name = "Bonaire, Sint Eustatius and Saba", Code="BES", Nationality = "Bonaire" },
            new Country() { Name = "Bosnia and Herzegovina", Code="BIH", Nationality = "Bosnian or Herzegovinian" },
            new Country() { Name = "Botswana", Code="BWA", Nationality = "Motswana, Botswanan" },
            new Country() { Name = "Bouvet Island", Code="BVT", Nationality = "Bouvet Island" },
            new Country() { Name = "Brazil", Code="BRA", Nationality = "Brazilian" },
            new Country() { Name = "British Indian Ocean Territory", Code="IOT", Nationality = "BIOT" },
            new Country() { Name = "Brunei Darussalam", Code="BRN", Nationality = "Bruneian" },
            new Country() { Name = "Bulgaria", Code="BGR", Nationality = "Bulgarian" },
            new Country() { Name = "Burkina Faso", Code="BFA", Nationality = "Burkinabé" },
            new Country() { Name = "Burundi", Code="BDI", Nationality = "Burundian" },
            new Country() { Name = "Cabo Verde", Code="CPV", Nationality = "Cabo Verdean" },
            new Country() { Name = "Cambodia", Code="KHM", Nationality = "Cambodian" },
            new Country() { Name = "Cameroon", Code="CMR", Nationality = "Cameroonian" },
            new Country() { Name = "Canada", Code="CAN", Nationality = "Canadian" },
            new Country() { Name = "Cayman Islands", Code="CYM", Nationality = "Caymanian" },
            new Country() { Name = "Central African Republic", Code="CAF", Nationality = "Central African" },
            new Country() { Name = "Chad", Code="TCD", Nationality = "Chadian" },
            new Country() { Name = "Chile", Code="CHL", Nationality = "Chilean" },
            new Country() { Name = "China", Code="CHN", Nationality = "Chinese" },
            new Country() { Name = "Christmas Island", Code="CXR", Nationality = "Christmas Island" },
            new Country() { Name = "Cocos (Keeling) Islands", Code="CCK", Nationality = "Cocos Island" },
            new Country() { Name = "Colombia", Code="COL", Nationality = "Colombian" },
            new Country() { Name = "Comoros", Code="COM", Nationality = "Comoran, Comorian" },
            new Country() { Name = "Congo (Republic of the)", Code="COG", Nationality = "Congolese" },
            new Country() { Name = "Congo (Democratic Republic of the)", Code="COD", Nationality = "Congolese" },
            new Country() { Name = "Cook Islands", Code="COK", Nationality = "Cook Island" },
            new Country() { Name = "Costa Rica", Code="CRI", Nationality = "Costa Rican" },
            new Country() { Name = "Côte d'Ivoire", Code="CIV", Nationality = "Ivorian" },
            new Country() { Name = "Croatia", Code="HRV", Nationality = "Croatian" },
            new Country() { Name = "Cuba", Code="CUB", Nationality = "Cuban" },
            new Country() { Name = "Curaçao", Code="CUW", Nationality = "Curaçaoan" },
            new Country() { Name = "Cyprus", Code="CYP", Nationality = "Cypriot" },
            new Country() { Name = "Czech Republic", Code="CZE", Nationality = "Czech" },
            new Country() { Name = "Denmark", Code="DNK", Nationality = "Danish" },
            new Country() { Name = "Djibouti", Code="DJI", Nationality = "Djiboutian" },
            new Country() { Name = "Dominica", Code="DMA", Nationality = "Dominican" },
            new Country() { Name = "Dominican Republic", Code="DOM", Nationality = "Dominican" },
            new Country() { Name = "Ecuador", Code="ECU", Nationality = "Ecuadorian" },
            new Country() { Name = "Egypt", Code="EGY", Nationality = "Egyptian" },
            new Country() { Name = "El Salvador", Code="SLV", Nationality = "Salvadoran" },
            new Country() { Name = "Equatorial Guinea", Code="GNQ", Nationality = "Equatorial Guinean, Equatoguinean" },
            new Country() { Name = "Eritrea", Code="ERI", Nationality = "Eritrean" },
            new Country() { Name = "Estonia", Code="EST", Nationality = "Estonian" },
            new Country() { Name = "Ethiopia", Code="ETH", Nationality = "Ethiopian" , DisplayOrder=1 },
            new Country() { Name = "Falkland Islands (Malvinas)", Code="FLK", Nationality = "Falkland Island" },
            new Country() { Name = "Faroe Islands", Code="FRO", Nationality = "Faroese" },
            new Country() { Name = "Fiji", Code="FJI", Nationality = "Fijian" },
            new Country() { Name = "Finland", Code="FIN", Nationality = "Finnish" },
            new Country() { Name = "France", Code="FRA", Nationality = "French" },
            new Country() { Name = "French Guiana", Code="GUF", Nationality = "French Guianese" },
            new Country() { Name = "French Polynesia", Code="PYF", Nationality = "French Polynesian" },
            new Country() { Name = "French Southern Territories", Code="ATF", Nationality = "French Southern Territories" },
            new Country() { Name = "Gabon", Code="GAB", Nationality = "Gabonese" },
            new Country() { Name = "Gambia", Code="GMB", Nationality = "Gambian" },
            new Country() { Name = "Georgia", Code="GEO", Nationality = "Georgian" },
            new Country() { Name = "Germany", Code="DEU", Nationality = "German" },
            new Country() { Name = "Ghana", Code="GHA", Nationality = "Ghanaian" },
            new Country() { Name = "Gibraltar", Code="GIB", Nationality = "Gibraltar" },
            new Country() { Name = "Greece", Code="GRC", Nationality = "Greek, Hellenic" },
            new Country() { Name = "Greenland", Code="GRL", Nationality = "Greenlandic" },
            new Country() { Name = "Grenada", Code="GRD", Nationality = "Grenadian" },
            new Country() { Name = "Guadeloupe", Code="GLP", Nationality = "Guadeloupe" },
            new Country() { Name = "Guam", Code="GUM", Nationality = "Guamanian, Guambat" },
            new Country() { Name = "Guatemala", Code="GTM", Nationality = "Guatemalan" },
            new Country() { Name = "Guernsey", Code="GGY", Nationality = "Channel Island" },
            new Country() { Name = "Guinea", Code="GIN", Nationality = "Guinean" },
            new Country() { Name = "Guinea-Bissau", Code="GNB", Nationality = "Bissau-Guinean" },
            new Country() { Name = "Guyana", Code="GUY", Nationality = "Guyanese" },
            new Country() { Name = "Haiti", Code="HTI", Nationality = "Haitian" },
            new Country() { Name = "Heard Island and McDonald Islands", Code="HMD", Nationality = "Heard Island or McDonald Islands" },
            new Country() { Name = "Vatican City State", Code="VAT", Nationality = "Vatican" },
            new Country() { Name = "Honduras", Code="HND", Nationality = "Honduran" },
            new Country() { Name = "Hong Kong", Code="HKG", Nationality = "Hong Kong, Hong Kongese" },
            new Country() { Name = "Hungary", Code="HUN", Nationality = "Hungarian, Magyar" },
            new Country() { Name = "Iceland", Code="ISL", Nationality = "Icelandic" },
            new Country() { Name = "India", Code="IND", Nationality = "Indian" },
            new Country() { Name = "Indonesia", Code="IDN", Nationality = "Indonesian" },
            new Country() { Name = "Iran", Code="IRN", Nationality = "Iranian, Persian" },
            new Country() { Name = "Iraq", Code="IRQ", Nationality = "Iraqi" },
            new Country() { Name = "Ireland", Code="IRL", Nationality = "Irish" },
            new Country() { Name = "Isle of Man", Code="IMN", Nationality = "Manx" },
            new Country() { Name = "Israel", Code="ISR", Nationality = "Israeli" },
            new Country() { Name = "Italy", Code="ITA", Nationality = "Italian" },
            new Country() { Name = "Jamaica", Code="JAM", Nationality = "Jamaican" },
            new Country() { Name = "Japan", Code="JPN", Nationality = "Japanese" },
            new Country() { Name = "Jersey", Code="JEY", Nationality = "Channel Island" },
            new Country() { Name = "Jordan", Code="JOR", Nationality = "Jordanian" },
            new Country() { Name = "Kazakhstan", Code="KAZ", Nationality = "Kazakhstani, Kazakh" },
            new Country() { Name = "Kenya", Code="KEN", Nationality = "Kenyan" },
            new Country() { Name = "Kiribati", Code="KIR", Nationality = "I-Kiribati" },
            new Country() { Name = "Korea (Democratic People's Republic of)", Code="PRK", Nationality = "North Korean" },
            new Country() { Name = "Korea (Republic of)", Code="KOR", Nationality = "South Korean" },
            new Country() { Name = "Kuwait", Code="KWT", Nationality = "Kuwaiti" },
            new Country() { Name = "Kyrgyzstan", Code="KGZ", Nationality = "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz" },
            new Country() { Name = "Lao People's Democratic Republic", Code="LAO", Nationality = "Lao, Laotian" },
            new Country() { Name = "Latvia", Code="LVA", Nationality = "Latvian" },
            new Country() { Name = "Lebanon", Code="LBN", Nationality = "Lebanese" },
            new Country() { Name = "Lesotho", Code="LSO", Nationality = "Basotho" },
            new Country() { Name = "Liberia", Code="LBR", Nationality = "Liberian" },
            new Country() { Name = "Libya", Code="LBY", Nationality = "Libyan" },
            new Country() { Name = "Liechtenstein", Code="LIE", Nationality = "Liechtenstein" },
            new Country() { Name = "Lithuania", Code="LTU", Nationality = "Lithuanian" },
            new Country() { Name = "Luxembourg", Code="LUX", Nationality = "Luxembourg, Luxembourgish" },
            new Country() { Name = "Macao", Code="MAC", Nationality = "Macanese, Chinese" },
            new Country() { Name = "Macedonia (the former Yugoslav Republic of)", Code="MKD", Nationality = "Macedonian" },
            new Country() { Name = "Madagascar", Code="MDG", Nationality = "Malagasy" },
            new Country() { Name = "Malawi", Code="MWI", Nationality = "Malawian" },
            new Country() { Name = "Malaysia", Code="MYS", Nationality = "Malaysian" },
            new Country() { Name = "Maldives", Code="MDV", Nationality = "Maldivian" },
            new Country() { Name = "Mali", Code="MLI", Nationality = "Malian, Malinese" },
            new Country() { Name = "Malta", Code="MLT", Nationality = "Maltese" },
            new Country() { Name = "Marshall Islands", Code="MHL", Nationality = "Marshallese" },
            new Country() { Name = "Martinique", Code="MTQ", Nationality = "Martiniquais, Martinican" },
            new Country() { Name = "Mauritania", Code="MRT", Nationality = "Mauritanian" },
            new Country() { Name = "Mauritius", Code="MUS", Nationality = "Mauritian" },
            new Country() { Name = "Mayotte", Code="MYT", Nationality = "Mahoran" },
            new Country() { Name = "Mexico", Code="MEX", Nationality = "Mexican" },
            new Country() { Name = "Micronesia (Federated States of)", Code="FSM", Nationality = "Micronesian" },
            new Country() { Name = "Moldova (Republic of)", Code="MDA", Nationality = "Moldovan" },
            new Country() { Name = "Monaco", Code="MCO", Nationality = "Monégasque, Monacan" },
            new Country() { Name = "Mongolia", Code="MNG", Nationality = "Mongolian" },
            new Country() { Name = "Montenegro", Code="MNE", Nationality = "Montenegrin" },
            new Country() { Name = "Montserrat", Code="MSR", Nationality = "Montserratian" },
            new Country() { Name = "Morocco", Code="MAR", Nationality = "Moroccan" },
            new Country() { Name = "Mozambique", Code="MOZ", Nationality = "Mozambican" },
            new Country() { Name = "Myanmar", Code="MMR", Nationality = "Burmese" },
            new Country() { Name = "Namibia", Code="NAM", Nationality = "Namibian" },
            new Country() { Name = "Nauru", Code="NRU", Nationality = "Nauruan" },
            new Country() { Name = "Nepal", Code="NPL", Nationality = "Nepali, Nepalese" },
            new Country() { Name = "Netherlands", Code="NLD", Nationality = "Dutch, Netherlandic" },
            new Country() { Name = "New Caledonia", Code="NCL", Nationality = "New Caledonian" },
            new Country() { Name = "New Zealand", Code="NZL", Nationality = "New Zealand, NZ" },
            new Country() { Name = "Nicaragua", Code="NIC", Nationality = "Nicaraguan" },
            new Country() { Name = "Niger", Code="NER", Nationality = "Nigerien" },
            new Country() { Name = "Nigeria", Code="NGA", Nationality = "Nigerian" },
            new Country() { Name = "Niue", Code="NIU", Nationality = "Niuean" },
            new Country() { Name = "Norfolk Island", Code="NFK", Nationality = "Norfolk Island" },
            new Country() { Name = "Northern Mariana Islands", Code="MNP", Nationality = "Northern Marianan" },
            new Country() { Name = "Norway", Code="NOR", Nationality = "Norwegian" },
            new Country() { Name = "Oman", Code="OMN", Nationality = "Omani" },
            new Country() { Name = "Pakistan", Code="PAK", Nationality = "Pakistani" },
            new Country() { Name = "Palau", Code="PLW", Nationality = "Palauan" },
            new Country() { Name = "Palestine, State of", Code="PSE", Nationality = "Palestinian" },
            new Country() { Name = "Panama", Code="PAN", Nationality = "Panamanian" },
            new Country() { Name = "Papua New Guinea", Code="PNG", Nationality = "Papua New Guinean, Papuan" },
            new Country() { Name = "Paraguay", Code="PRY", Nationality = "Paraguayan" },
            new Country() { Name = "Peru", Code="PER", Nationality = "Peruvian" },
            new Country() { Name = "Philippines", Code="PHL", Nationality = "Philippine, Filipino" },
            new Country() { Name = "Pitcairn", Code="PCN", Nationality = "Pitcairn Island" },
            new Country() { Name = "Poland", Code="POL", Nationality = "Polish" },
            new Country() { Name = "Portugal", Code="PRT", Nationality = "Portuguese" },
            new Country() { Name = "Puerto Rico", Code="PRI", Nationality = "Puerto Rican" },
            new Country() { Name = "Qatar", Code="QAT", Nationality = "Qatari" },
            new Country() { Name = "Réunion", Code="REU", Nationality = "Réunionese, Réunionnais" },
            new Country() { Name = "Romania", Code="ROU", Nationality = "Romanian" },
            new Country() { Name = "Russian Federation", Code="RUS", Nationality = "Russian" },
            new Country() { Name = "Rwanda", Code="RWA", Nationality = "Rwandan" },
            new Country() { Name = "Saint Barthélemy", Code="BLM", Nationality = "Barthélemois" },
            new Country() { Name = "Saint Helena, Ascension and Tristan da Cunha", Code="SHN", Nationality = "Saint Helenian" },
            new Country() { Name = "Saint Kitts and Nevis", Code="KNA", Nationality = "Kittitian or Nevisian" },
            new Country() { Name = "Saint Lucia", Code="LCA", Nationality = "Saint Lucian" },
            new Country() { Name = "Saint Martin (French part)", Code="MAF", Nationality = "Saint-Martinoise" },
            new Country() { Name = "Saint Pierre and Miquelon", Code="SPM", Nationality = "Saint-Pierrais or Miquelonnais" },
            new Country() { Name = "Saint Vincent and the Grenadines", Code="VCT", Nationality = "Saint Vincentian, Vincentian" },
            new Country() { Name = "Samoa", Code="WSM", Nationality = "Samoan" },
            new Country() { Name = "San Marino", Code="SMR", Nationality = "Sammarinese" },
            new Country() { Name = "Sao Tome and Principe", Code="STP", Nationality = "São Toméan" },
            new Country() { Name = "Saudi Arabia", Code="SAU", Nationality = "Saudi, Saudi Arabian" },
            new Country() { Name = "Senegal", Code="SEN", Nationality = "Senegalese" },
            new Country() { Name = "Serbia", Code="SRB", Nationality = "Serbian" },
            new Country() { Name = "Seychelles", Code="SYC", Nationality = "Seychellois" },
            new Country() { Name = "Sierra Leone", Code="SLE", Nationality = "Sierra Leonean" },
            new Country() { Name = "Singapore", Code="SGP", Nationality = "Singaporean" },
            new Country() { Name = "Sint Maarten (Dutch part)", Code="SXM", Nationality = "Sint Maarten" },
            new Country() { Name = "Slovakia", Code="SVK", Nationality = "Slovak" },
            new Country() { Name = "Slovenia", Code="SVN", Nationality = "Slovenian, Slovene" },
            new Country() { Name = "Solomon Islands", Code="SLB", Nationality = "Solomon Island" },
            new Country() { Name = "Somalia", Code="SOM", Nationality = "Somali, Somalian" },
            new Country() { Name = "South Africa", Code="ZAF", Nationality = "South African" },
            new Country() { Name = "South Georgia and the South Sandwich Islands", Code="SGS", Nationality = "South Georgia or South Sandwich Islands" },
            new Country() { Name = "South Sudan", Code="SSD", Nationality = "South Sudanese" },
            new Country() { Name = "Spain", Code="ESP", Nationality = "Spanish" },
            new Country() { Name = "Sri Lanka", Code="LKA", Nationality = "Sri Lankan" },
            new Country() { Name = "Sudan", Code="SDN", Nationality = "Sudanese" },
            new Country() { Name = "Suriname", Code="SUR", Nationality = "Surinamese" },
            new Country() { Name = "Svalbard and Jan Mayen", Code="SJM", Nationality = "Svalbard" },
            new Country() { Name = "Swaziland", Code="SWZ", Nationality = "Swazi" },
            new Country() { Name = "Sweden", Code="SWE", Nationality = "Swedish" },
            new Country() { Name = "Switzerland", Code="CHE", Nationality = "Swiss" },
            new Country() { Name = "Syrian Arab Republic", Code="SYR", Nationality = "Syrian" },
            new Country() { Name = "Taiwan, Province of China", Code="TWN", Nationality = "Chinese, Taiwanese" },
            new Country() { Name = "Tajikistan", Code="TJK", Nationality = "Tajikistani" },
            new Country() { Name = "Tanzania, United Republic of", Code="TZA", Nationality = "Tanzanian" },
            new Country() { Name = "Thailand", Code="THA", Nationality = "Thai" },
            new Country() { Name = "Timor-Leste", Code="TLS", Nationality = "Timorese" },
            new Country() { Name = "Togo", Code="TGO", Nationality = "Togolese" },
            new Country() { Name = "Tokelau", Code="TKL", Nationality = "Tokelauan" },
            new Country() { Name = "Tonga", Code="TON", Nationality = "Tongan" },
            new Country() { Name = "Trinidad and Tobago", Code="TTO", Nationality = "Trinidadian or Tobagonian" },
            new Country() { Name = "Tunisia", Code="TUN", Nationality = "Tunisian" },
            new Country() { Name = "Turkey", Code="TUR", Nationality = "Turkish" },
            new Country() { Name = "Turkmenistan", Code="TKM", Nationality = "Turkmen" },
            new Country() { Name = "Turks and Caicos Islands", Code="TCA", Nationality = "Turks and Caicos Island" },
            new Country() { Name = "Tuvalu", Code="TUV", Nationality = "Tuvaluan" },
            new Country() { Name = "Uganda", Code="UGA", Nationality = "Ugandan" },
            new Country() { Name = "Ukraine", Code="UKR", Nationality = "Ukrainian" },
            new Country() { Name = "United Arab Emirates", Code="ARE", Nationality = "Emirati, Emirian, Emiri" },
            new Country() { Name = "United Kingdom of Great Britain and Northern Ireland", Code="GBR", Nationality = "British, UK" },
            new Country() { Name = "United States Minor Outlying Islands", Code="UMI", Nationality = "American" },
            new Country() { Name = "United States of America", Code="USA", Nationality = "American", DisplayOrder=2 },
            new Country() { Name = "Uruguay", Code="URY", Nationality = "Uruguayan" },
            new Country() { Name = "Uzbekistan", Code="UZB", Nationality = "Uzbekistani, Uzbek" },
            new Country() { Name = "Vanuatu", Code="VUT", Nationality = "Ni-Vanuatu, Vanuatuan" },
            new Country() { Name = "Venezuela (Bolivarian Republic of)", Code="VEN", Nationality = "Venezuelan" },
            new Country() { Name = "Vietnam", Code="VNM", Nationality = "Vietnamese" },
            new Country() { Name = "Virgin Islands (British)", Code="VGB", Nationality = "British Virgin Island" },
            new Country() { Name = "Virgin Islands (U.S.)", Code="VIR", Nationality = "U.S. Virgin Island" },
            new Country() { Name = "Wallis and Futuna", Code="WLF", Nationality = "Wallis and Futuna, Wallisian or Futunan" },
            new Country() { Name = "Western Sahara", Code="ESH", Nationality = "Sahrawi, Sahrawian, Sahraouian" },
            new Country() { Name = "Yemen", Code="YEM", Nationality = "Yemeni" },
            new Country() { Name = "Zambia", Code="ZMB", Nationality = "Zambian" },
            new Country() { Name = "Zimbabwe", Code="ZWE", Nationality = "Zimbabwean" }
        };
    }
}
