using SMS.Domain;

namespace SMS.Persistence.SeedData
{
    public static class ForeignCurrencyTypeSeedData
    {
        public static async Task SeedAsync(SMSDbContext ctx)
        {
            if (ctx.ForeignCurrencyTypes.Any()) return;

            var foreignCurrencyTypes = new List<ForeignCurrencyType>() {
                    new ForeignCurrencyType{Name = "AED", Description = "United Arab Emirates dirham", DisplayOrder = 5},
                    new ForeignCurrencyType{Name = "AFN", Description = "Afghan afghani", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ALL", Description = "Albanian lek", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "AMD", Description = "Armenian dram", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ANG", Description = "Netherlands Antillean guilder", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "AOA", Description = "Angolan kwanza", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ARS", Description = "Argentine peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "AUD", Description = "Australian dollar", DisplayOrder = 7},
                    new ForeignCurrencyType{Name = "AWG", Description = "Aruban florin", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "AZN", Description = "Azerbaijani manat", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BAM", Description = "Bosnia and Herzegovina convertible mark", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BBD", Description = "Barbados dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BDT", Description = "Bangladeshi taka", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BGN", Description = "Bulgarian lev", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BHD", Description = "Bahraini dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BIF", Description = "Burundian franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BMD", Description = "Bermudian dollar (customarily known as Bermuda dollar)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BND", Description = "Brunei dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BOB", Description = "Boliviano", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BRL", Description = "Brazilian real", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BSD", Description = "Bahamian dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BTN", Description = "Bhutanese ngultrum", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BWP", Description = "Botswana pula", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BYR", Description = "Belarusian ruble", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "BZD", Description = "Belize dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CAD", Description = "Canadian dollar", DisplayOrder = 4},
                    new ForeignCurrencyType{Name = "CDF", Description = "Congolese franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CHF", Description = "Swiss franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CHW", Description = "WIR Franc (complementary currency)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CLP", Description = "Chilean peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CNY", Description = "Chinese yuan", DisplayOrder = 8},
                    new ForeignCurrencyType{Name = "COP", Description = "Colombian peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "COU", Description = "Unidad de Valor Real", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CRC", Description = "Costa Rican colon", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CUC", Description = "Cuban convertible peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CUP", Description = "Cuban peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CVE", Description = "Cape Verde escudo", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "CZK", Description = "Czech koruna", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "DJF", Description = "Djiboutian franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "DKK", Description = "Danish krone", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "DOP", Description = "Dominican peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "DZD", Description = "Algerian dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "EGP", Description = "Egyptian pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ERN", Description = "Eritrean nakfa", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ETB", Description = "Ethiopian birr", DisplayOrder = 0},
                    new ForeignCurrencyType{Name = "EUR", Description = "Euro", DisplayOrder = 3},
                    new ForeignCurrencyType{Name = "FJD", Description = "Fiji dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "FKP", Description = "Falkland Islands pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GBP", Description = "Pound sterling", DisplayOrder = 4},
                    new ForeignCurrencyType{Name = "GEL", Description = "Georgian lari", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GHS", Description = "Ghanaian cedi", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GIP", Description = "Gibraltar pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GMD", Description = "Gambian dalasi", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GNF", Description = "Guinean franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GTQ", Description = "Guatemalan quetzal", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "GYD", Description = "Guyanese dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "HKD", Description = "Hong Kong dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "HNL", Description = "Honduran lempira", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "HRK", Description = "Croatian kuna", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "HTG", Description = "Haitian gourde", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "HUF", Description = "Hungarian forint", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "IDR", Description = "Indonesian rupiah", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ILS", Description = "Israeli new shekel", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "INR", Description = "Indian rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "IQD", Description = "Iraqi dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "IRR", Description = "Iranian rial", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ISK", Description = "Icelandic króna", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "JMD", Description = "Jamaican dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "JOD", Description = "Jordanian dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "JPY", Description = "Japanese yen", DisplayOrder = 9},
                    new ForeignCurrencyType{Name = "KES", Description = "Kenyan shilling", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KGS", Description = "Kyrgyzstani som", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KHR", Description = "Cambodian riel", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KMF", Description = "Comoro franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KPW", Description = "North Korean won", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KRW", Description = "South Korean won", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KWD", Description = "Kuwaiti dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KYD", Description = "Cayman Islands dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "KZT", Description = "Kazakhstani tenge", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LAK", Description = "Lao kip", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LBP", Description = "Lebanese pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LKR", Description = "Sri Lankan rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LRD", Description = "Liberian dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LSL", Description = "Lesotho loti", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LTL", Description = "Lithuanian litas", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LVL", Description = "Latvian lats", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "LYD", Description = "Libyan dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MAD", Description = "Moroccan dirham", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MDL", Description = "Moldovan leu", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MGA", Description = "Malagasy ariary", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MKD", Description = "Macedonian denar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MMK", Description = "Myanma kyat", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MNT", Description = "Mongolian tugrik", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MOP", Description = "Macanese pataca", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MRO", Description = "Mauritanian ouguiya", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MUR", Description = "Mauritian rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MVR", Description = "Maldivian rufiyaa", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MWK", Description = "Malawian kwacha", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MXN", Description = "Mexican peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MYR", Description = "Malaysian ringgit", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "MZN", Description = "Mozambican metical", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NAD", Description = "Namibian dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NGN", Description = "Nigerian naira", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NIO", Description = "Nicaraguan córdoba", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NOK", Description = "Norwegian krone", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NPR", Description = "Nepalese rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "NZD", Description = "New Zealand dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "OMR", Description = "Omani rial", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PAB", Description = "Panamanian balboa", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PEN", Description = "Peruvian nuevo sol", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PGK", Description = "Papua New Guinean kina", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PHP", Description = "Philippine peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PKR", Description = "Pakistani rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PLN", Description = "Polish złoty", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "PYG", Description = "Paraguayan guaraní", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "QAR", Description = "Qatari riyal", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "RON", Description = "Romanian new leu", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "RSD", Description = "Serbian dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "RUB", Description = "Russian rouble", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "RWF", Description = "Rwandan franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SAR", Description = "Saudi riyal", DisplayOrder = 6},
                    new ForeignCurrencyType{Name = "SBD", Description = "Solomon Islands dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SCR", Description = "Seychelles rupee", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SDG", Description = "Sudanese pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SEK", Description = "Swedish krona/kronor", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SGD", Description = "Singapore dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SHP", Description = "Saint Helena pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SLL", Description = "Sierra Leonean leone", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SOS", Description = "Somali shilling", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SRD", Description = "Surinamese dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SSP", Description = "South Sudanese pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "STD", Description = "São Tomé and Príncipe dobra", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SYP", Description = "Syrian pound", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "SZL", Description = "Swazi lilangeni", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "THB", Description = "Thai baht", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TJS", Description = "Tajikistani somoni", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TMT", Description = "Turkmenistani manat", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TND", Description = "Tunisian dinar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TOP", Description = "Tongan paʻanga", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TRY", Description = "Turkish lira", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TTD", Description = "Trinidad and Tobago dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TWD", Description = "New Taiwan dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "TZS", Description = "Tanzanian shilling", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "UAH", Description = "Ukrainian hryvnia", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "UGX", Description = "Ugandan shilling", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "USD", Description = "United States dollar", DisplayOrder = 1},
                    new ForeignCurrencyType{Name = "UYU", Description = "Uruguayan peso", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "UZS", Description = "Uzbekistan som", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "VEF", Description = "Venezuelan bolívar fuerte", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "VND", Description = "Vietnamese dong", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "VUV", Description = "Vanuatu vatu", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "WST", Description = "Samoan tala", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XAF", Description = "CFA franc BEAC", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XAG", Description = "Silver (one troy ounce)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XAU", Description = "Gold (one troy ounce)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XCD", Description = "East Caribbean dollar", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XDR", Description = "Special drawing rights", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XFU", Description = "UIC franc (special settlement currency)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XOF", Description = "CFA franc BCEAO", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XPD", Description = "Palladium (one troy ounce)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XPF", Description = "CFP franc", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XPT", Description = "Platinum (one troy ounce)", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XTS", Description = "Code reserved for testing purposes", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "XXX", Description = "No currency", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "YER", Description = "Yemeni rial", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ZAR", Description = "South African rand", DisplayOrder = 1000},
                    new ForeignCurrencyType{Name = "ZMW", Description = "Zambian kwacha", DisplayOrder = 1000 }
            };

            await ctx.ForeignCurrencyTypes.AddRangeAsync(foreignCurrencyTypes);
        }
    }
}
